### PR TITLE
check sha256 fingerprint

### PR DESCRIPTION
**Pull request by pomverte**
- download file
- create the checksum file
- check fingerprint
- unarchive
- remove archive

### CODE REVIEW

**Comment by msiegenthaler** [comment]
Shouldn’t the sha sum be an arg?

**Comment by pomverte** [comment]
It depends on how we are building the image : 
is it using `--build-arg` ?
or every time a version upgrade occurs the `Dockerfile` is changed ?

To be consistent, if `VERSION` is `ARG` then `SHA256SUM` should also be `ARG`

However, `FILENAME` should not be `ARG` but `ENV` in my opinion
since it build using `VERSION` otherwise the build stage could be broken this way : 

`docker build -t linkyard/docker-helm --build-arg FILENAME='foo' .`

What do you think ?

**Comment by pomverte** [comment]
I see that, this was previously addressed with the following commit 
https://github.com/linkyard/docker-helm/commit/3fea824b7130841be07b396c40efbcfc3e5c9572

**Comment by pomverte** [comment]
> ENV is for run-time
> ARG for build-time

@tmaier is right

But this is a multi stage build, in the final image here is what environnement contains : 
```
env
HOSTNAME=903c4eca0f72
SHLVL=1
HOME=/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
```

**Comment by msiegenthaler** [comment]
Very good point! Sorry I’m always a bit unsure when to use which. 
So let’s change both to env

**Pull request merged**
